### ISSUE TITLE
Missing attribution

### ISSUE THREAD

**Issue by pyfisch** [oxigraph/oxilangtag#2]
Hello @Tpt,
[your comment](https://github.com/pyfisch/rust-language-tags/issues/21#issuecomment-819448874) brought to my attention that you publish your own language tags crate and use some of the code from my original crate. That's fine, I like it when code that I've written is used in other projects. I especially appreciate it that you contributed a rewrite of the language-tags crate.

What I don't like is that when you published your own crate you copied parts of the language-tags crate without attributing the authors and preserving the git history of the code. One example that is the [`parse_langtag`](https://github.com/oxigraph/oxilangtag/blob/ca8e5ad7bac0b3b3950bbdfb23fd9dabdb267816/src/lib.rs#L630). Please restore the git history and mention me and the other authors as required by the - already very permissive - MIT license.

**Comment by Tpt** [comment]
Hi! Sorry for the misunderstanding. As you said I rewrote the language-tags crate and then reused some of my rewritten code for this crate. So, I believe that I am the copyright owner for this code and so could use it anywhere else. But indeed there are some significant inspiration from your code. I should have credited them. I have added a mention of it in the "licensing" section of the README: ff492b78eda2a9419eb8472d5bf5343e8f066f09
Sorry again.

**Comment by pyfisch** [comment]
Thank you for reacting so quickly! I don' think it would be appropriate to mention me in the Cargo.toml, considering I am not maintaining this crate and there is comparatively little code written by me.

> If you want, I can also submit pull request to your crates in order to delete this fork, I mostly did it because I feared you completely dropped from maintaining the language-tags crate.

I have been maintaining the language-tags crate passively: I would react to PRs and issues but didn't write much code myself. It usually helps if I am pinged, if I forget to do something. Sorry for giving you the impression that I dropped maintaining the crate.

I think it is beneficial to the rust ecosystem if there is just one crate to provide some basic functionality like language tags. Additionally it is always preferable to have a truck number larger than one for a crate. :wink: For these reasons I would support merging the oxilangtag and language-tags crates. If you maintain a language tags crate, I will gladly do code reviews and help with issues and releases. This crate can be part of oxigraph org.

Do you know which major differences there are between oxilangtag and language-tags right now?

**Comment by Tpt** [comment]
Sorry for the very late answer.

It's great to ear that you still maintain the language tags crate.

+1 to having a single crate if it allows to provide enough for the different needs and thank you so much for the very nice and kind proposal.

oxilangtag is very focus on the Oxigraph/RDF use case: being able to validate is a language tag is well-formed. There is no canonicalization, case normalization... So it's feature scope is pretty closed and I basically have not needed to update it after its first release. Outside of the "missing" features the main difference is that oxilangtag allows zero copy validation and to choose which buffer to use internally.

The oxigraph org is very focused on Oxigraph itself so it might not be a good place for a general use language crate. Your crate is much more used than oxilangtag so it might make sense to keep your crate where it is and merge oxilangtag in it if its specific features (zero-copy validation...) do not conflict with language-tags design to much.

**Comment by pyfisch** [comment]
> Sorry for the very late answer.

Sorry for my late answer as well.

Yeah, in this case its better to keep the crates separate. However I think rust-language-tags should link oxilangtag and describe when it is a more lightweight alternative.
